"use client";

import { useState } from "react";
import { Sparkles, Loader2, Send } from "lucide-react";

import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
  SheetFooter,
  SheetClose,
} from "@shared/ui/sheet";
import { Button } from "@shared/ui/button";
import { Input } from "@shared/ui/input";
import { Label } from "@shared/ui/label";
import { Textarea } from "@shared/ui/textarea";

export function NewFeatureDrawer() {
  const [isOpen, setIsOpen] = useState(false);
  const [isExpanding, setIsExpanding] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [featureName, setFeatureName] = useState("");
  const [userStory, setUserStory] = useState("");

  const handleExpand = (e: React.MouseEvent) => {
    e.preventDefault();
    setIsExpanding(true);
    // Simulate AI generation
    setTimeout(() => {
      setUserStory(
        (prev) =>
          prev +
          (prev ? "\n\n" : "") +
          "### Requirements Generated by AI Context Manager\n" +
          "- [x] Needs to integrate with existing PostgreSQL schema.\n" +
          "- [x] Needs a high-priority tag for immediate execution.\n" +
          "- [x] Should emit real-time logs to the UI via tRPC.\n\n" +
          "### Suggested Approach\n" +
          "We will split this into 3 agent tasks:\n" +
          "1. **Frontend**: Add a 'Turbo Mode' toggle to the QueueList component.\n" +
          "2. **Backend**: Extend the TRPC router to accept a `priority` flag.\n" +
          "3. **Database**: Migration to add `priority` column to `FeatureQueue`.",
      );
      setIsExpanding(false);
    }, 1500);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    // Simulate submission and redirect/refresh
    setTimeout(() => {
      setIsSubmitting(false);
      setIsOpen(false);
      setFeatureName("");
      setUserStory("");
      // Ideally trigger a revalidation or state update here
      window.location.reload();
    }, 800);
  };

  return (
    <Sheet open={isOpen} onOpenChange={setIsOpen}>
      <SheetTrigger asChild>
        <Button className="gap-2 shadow-lg shadow-primary/20 hover:shadow-primary/30 transition-all rounded-full px-6">
          <Sparkles className="h-4 w-4" />
          New Feature
        </Button>
      </SheetTrigger>
      <SheetContent className="sm:max-w-[425px] flex flex-col gap-0 p-0 border-l border-border/50 bg-background/95 backdrop-blur-xl">
        <SheetHeader className="px-6 py-6 border-b border-border/50 bg-muted/20">
          <SheetTitle className="text-2xl font-bold flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            Copilot Create
          </SheetTitle>
          <SheetDescription className="text-sm leading-relaxed">
            Describe your feature in plain English. Our AI Context Manager will
            automatically draft the PRD and architect the task swarm.
          </SheetDescription>
        </SheetHeader>

        <form
          onSubmit={handleSubmit}
          className="flex flex-col flex-1 overflow-hidden"
        >
          <div className="flex-1 overflow-y-auto px-6 py-6 space-y-6">
            <div className="space-y-2">
              <Label htmlFor="title" className="text-foreground/80 font-medium">
                Feature Title
              </Label>
              <Input
                id="title"
                placeholder="e.g., Integrate Stripe Subscription"
                value={featureName}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                  setFeatureName(e.target.value)
                }
                className="bg-background/50 border-border shadow-sm focus-visible:ring-primary/20 transition-all"
                required
              />
            </div>

            <div className="space-y-2 relative">
              <div className="flex items-center justify-between">
                <Label
                  htmlFor="story"
                  className="text-foreground/80 font-medium"
                >
                  User Story & Requirements
                </Label>
                <button
                  type="button"
                  onClick={handleExpand}
                  disabled={isExpanding}
                  className="text-xs font-semibold text-primary hover:text-primary/80 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1.5 px-2 py-1 rounded-md hover:bg-primary/10 transition-all"
                >
                  {isExpanding ? (
                    <Loader2 className="h-3 w-3 animate-spin" />
                  ) : (
                    <Sparkles className="h-3 w-3" />
                  )}
                  Mock Magic Expand
                </button>
              </div>
              <Textarea
                id="story"
                placeholder="As a user, I want to..."
                className="min-h-[250px] resize-none bg-background/50 border-border shadow-sm focus-visible:ring-primary/20 transition-all font-mono text-sm"
                value={userStory}
                onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                  setUserStory(e.target.value)
                }
                required
              />
              {isExpanding && (
                <div className="absolute inset-0 flex items-center justify-center bg-background/60 backdrop-blur-sm rounded-md border border-border/50 z-10 transition-all">
                  <div className="flex flex-col items-center gap-3">
                    <Loader2 className="h-6 w-6 animate-spin text-primary" />
                    <span className="text-xs font-medium text-foreground animate-pulse">
                      Context Manager analyzing...
                    </span>
                  </div>
                </div>
              )}
            </div>

            <div className="space-y-3 pt-4 border-t border-border/50">
              <Label className="text-foreground/80 font-medium">
                Execution Priority
              </Label>
              <div className="grid grid-cols-2 gap-3">
                {/* Mock logic for now, UI only */}
                <div className="border border-primary bg-primary/10 rounded-lg p-3 cursor-pointer ring-2 ring-primary/20 transition-all">
                  <div className="font-semibold text-primary text-sm mb-1">
                    Turbo Mode
                  </div>
                  <div className="text-xs text-muted-foreground">
                    Swarm (5 agents)
                  </div>
                </div>
                <div className="border border-border/50 bg-background/50 rounded-lg p-3 cursor-pointer hover:border-border transition-all opacity-70 hover:opacity-100">
                  <div className="font-semibold text-foreground text-sm mb-1">
                    Standard
                  </div>
                  <div className="text-xs text-muted-foreground">
                    Single Agent
                  </div>
                </div>
              </div>
            </div>
          </div>

          <SheetFooter className="px-6 py-5 border-t border-border/50 bg-muted/10 sm:justify-between items-center shrink-0">
            <SheetClose asChild>
              <Button
                type="button"
                variant="ghost"
                className="hover:bg-destructive/10 hover:text-destructive"
              >
                Cancel
              </Button>
            </SheetClose>
            <Button
              type="submit"
              disabled={
                isSubmitting || !featureName.trim() || !userStory.trim()
              }
              className="gap-2 shadow-lg shadow-primary/20"
            >
              {isSubmitting ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Send className="h-4 w-4" />
              )}
              Deploy Agents
            </Button>
          </SheetFooter>
        </form>
      </SheetContent>
    </Sheet>
  );
}
